Repository hongik-devtalk/Devtalk-Client-Application, pull requests merged in 2025-10, with the labels that each got.

#82 [UI] 어드민 세미나 상세정보 관리 및 세미나 추가하기 페이지 구현
  src/components/admin/SeminarManage/ActiveDateForm.tsx
  src/components/admin/SeminarManage/ReviewList.tsx
  src/components/admin/SeminarManage/SeminarForm.tsx
  src/components/admin/SeminarManage/SingleSpeakerForm.tsx
  src/components/admin/SeminarManage/SpeakerForm.tsx
  src/components/admin/SeminarManage/StarRating.tsx
  src/components/admin/seminar-manage/ActivationDate/ActiveDateForm.tsx
  src/components/admin/seminar-manage/ActivationDate/CustomSelect.tsx
  src/components/admin/seminar-manage/ActivationDate/DateTimeSelector.tsx
  src/components/admin/seminar-manage/Footer.tsx
  src/components/admin/seminar-manage/Header.tsx
  src/components/admin/seminar-manage/LiveLink/LiveLinkInput.tsx
  src/components/admin/seminar-manage/MainContent.tsx
  src/components/admin/seminar-manage/Review/ReivewItem.tsx
  src/components/admin/seminar-manage/Review/ReviewList.tsx
  src/components/admin/seminar-manage/Review/StarRating.tsx
  src/components/admin/seminar-manage/SeminarCard/SeminarCard.tsx
  src/components/admin/seminar-manage/SeminarDetail/FormField.tsx
  src/components/admin/seminar-manage/SeminarDetail/SeminarForm.tsx
  src/components/admin/seminar-manage/Speaker/SingleSpeakerForm.tsx
  src/components/admin/seminar-manage/Speaker/SpeakerForm.tsx
  src/hooks/SeminarManage/useReviewActions.ts
  src/hooks/SeminarManage/useSeminarState.ts
  src/pages/admin/seminar-manage/Add.tsx
  src/pages/admin/seminar-manage/Cards.tsx
  src/pages/admin/seminar-manage/Detail.tsx
  src/styles/formInput.css
  src/types/SeminarManage/seminar.ts
Labels: 🎨 Html&css, 준석

#98 [FIX] import 경로 오류 해결
  src/components/admin/home/HomeReviewItem.tsx
Labels: 🐞 BugFix, 준석

#94 [CHORE] 배포용 빌드 스크립트 및 GitHub Actions 작성
  .github/workflows/deploy.yml
  build.sh
Labels: 🌏 Deploy, 준희

#104 [FEAT] 세미나 신청폼 이메일 필드 추가 및 디테일 구현
  src/components/SeminarApply/ApplyForm.tsx
  src/components/SeminarApply/EmailSection.tsx
  src/components/SeminarApply/PhoneSection.tsx
  src/components/SeminarApply/StudentIdSection.tsx
  src/utils/formatPhoneNumber.ts
  src/utils/formatStudentId.ts
  src/utils/validators.ts
Labels: ✨ Feature, 유민

#107 [SETTING] 공통 응답 타입 세팅
  src/types/common.ts
Labels: ⚙ Setting, 📬 API, 유민

#95 [UI] 홈 화면 내 스크롤 구현
  src/components/common/HamburgerBar.tsx
  src/components/common/Header.tsx
  src/pages/user/home/Home.tsx
Labels: 🎨 Html&css, 채윤

#123 [FEAT] 어드민 사이드바 하이라이트 기능 추가
  src/layouts/admin/Sidebar.tsx
Labels: 🎨 Html&css, 준희

#109 [CHORE] axiosInstance 및 헤더 토큰 설정
  package-lock.json
  package.json
  src/apis/adminInstance.ts
  src/apis/userInstance.ts
  src/constants/key.ts
Labels: 📬 API, 수진

#131 [FEAT] 어드민 로그인 API 연동
  src/apis/auth.api.ts
  src/pages/admin/login/Login.tsx
  src/types/auth.types.ts
Labels: 📬 API, 윤지

#130 [UI] 세미나 상세 페이지 스크롤 구현
  src/components/Seminar/SeminarDetailCard.tsx
  src/hooks/useIsVisible.tsx
  src/pages/user/seminar/Detail.tsx
Labels: 🎨 Html&css, 수진

#134 [FIX] 어드민 레이아웃 오류 해결
  src/layouts/admin/AdminLayout.tsx
  src/layouts/admin/Sidebar.tsx
Labels: 🐞 BugFix, 준석

#121 [FEAT] 신청하기 팝업 모달 구현 및 라우팅 방식 수정
  src/App.tsx
  src/components/Modal/ApplyAlertModal.tsx
  src/components/Modal/ApplyExitModal.tsx
  src/components/Modal/ApplySuccessModal.tsx
  src/components/SeminarApply/ApplyHeader.tsx
  src/pages/admin/login/Login.tsx
  src/pages/user/seminar/ApplyInfo.tsx
  src/pages/user/seminar/ApplyQuestion.tsx
  src/routes/admin/AdminProtectedRoutes.tsx
  src/routes/admin/AdminPublicRoutes.tsx
  src/routes/admin/index.ts
  src/routes/index.ts
  src/routes/user/UserProtectedRoutes.tsx
  src/routes/user/UserPublicRoutes.tsx
  src/routes/user/index.ts
Labels: 🎨 Html&css, 윤지

#142 [FEAT] 로딩스피너 구현
  package-lock.json
  package.json
  src/components/common/LoadingSpinner.tsx
Labels: 🎨 Html&css, 유민

#148 [FEAT] 어드민 홈화면 관리 - 홍보 사진 관리 화면 api 연동
  src/apis/HomeManage/homeImageApi.ts
  src/components/admin/upload/AdminFileUpload.tsx
  src/components/admin/upload/AdminImageUpload.tsx
  src/components/admin/upload/AdminPresentationUpload.tsx
  src/constants/queryKey.ts
  src/hooks/HomeManage/useHomeImage.ts
  src/pages/admin/home-manage/PromoImage.tsx
  src/types/HomeManage/homeImage.api.ts
Labels: 📬 API, 윤지

#147 [UI] 세미나 당일 홈 UI
  src/assets/icons/common/devtalkTicket.png
  src/components/common/Cta.tsx
  src/pages/user/home/Home.tsx
Labels: 🎨 Html&css, 채윤

#150 [FEAT] 세미나 신청폼 API 연동 및 입력 정보 상태 관리
  package-lock.json
  package.json
  src/apis/seminarApply.ts
  src/components/SeminarApply/ApplyForm.tsx
  src/components/SeminarApply/AutoResizeTextarea.tsx
  src/components/SeminarApply/DepartmentSection.tsx
  src/components/SeminarApply/EmailSection.tsx
  src/components/SeminarApply/GradeSection.tsx
  src/components/SeminarApply/HowToKnowSection.tsx
  src/components/SeminarApply/NameSection.tsx
  src/components/SeminarApply/ParticipateSection.tsx
  src/components/SeminarApply/PhoneSection.tsx
  src/components/SeminarApply/StudentIdSection.tsx
  src/components/common/ScrollToTop.tsx
  src/constants/seminarApplyInfo.ts
  src/layouts/user/UserLayout.tsx
  src/pages/user/seminar/ApplyInfo.tsx
  src/pages/user/seminar/ApplyQuestion.tsx
  src/stores/useApplyDraft.ts
  src/types/Applicants/seminarApply.ts
  src/utils/mapEnums.ts
  src/utils/validators.ts
Labels: ✨ Feature, 📬 API, 유민

#152 [FEAT] 세미나 홈 api 연결
  src/apis/seminarList.ts
  src/components/Seminar/SeminarListCard.tsx
  src/pages/user/seminar/Home.tsx
Labels: 📬 API, 수진

#164 [CHORE] 세미나 상세 페이지 CTA props 받도록 변경
  src/pages/user/seminar/Detail.tsx
Labels: 🐞 BugFix, 수진

#154 [FEAT] 로그아웃 API 연동 및 파일 정리
  src/apis/HomeManage/homeImageApi.ts
  src/apis/auth.api.ts
  src/apis/authApi.ts
  src/hooks/HomeManage/useHomeImage.ts
  src/layouts/admin/Sidebar.tsx
  src/pages/admin/login/Login.tsx
  src/types/HomeManage/homeImage.ts
  src/types/auth.ts
Labels: 📬 API, 윤지

#170 [FEAT] 세미나 리뷰작성 api 연결
  src/apis/seminarReview.ts
  src/apis/userInstance.ts
  src/components/Seminar/SeminarReviewForm.tsx
  src/components/Seminar/SeminarReviewInput.tsx
  src/pages/user/seminar/Review.tsx
  src/types/seminarReview.ts
Labels: 📬 API, 수진
