Repository hongik-devtalk/Devtalk-Client-Application, pull requests merged in 2025-09, with the labels that each got.

#4 [FIX] Delete CR 에러 해결
  eslint.config.js
Labels: 🐞 BugFix, 유민

#6 [REFACTOR] 디자인 토큰 수정
  src/styles/theme.css
  src/styles/utilities.css
Labels: 유민, 🔨 Refactor

#10 [FEAT] 푸터 컴포넌트 구현
  src/assets/icons/components/Footer/link.svg
  src/assets/icons/components/Footer/mail.svg
  src/assets/icons/components/Footer/messagecircle.svg
  src/assets/logos/devlogo.svg
  src/components/common/Footer.tsx
  src/index.css
Labels: 🎨 Html&css, 유민

#9 [FEAT] 페이지 라우팅 설정
  package-lock.json
  src/App.tsx
  src/pages/admin/auth-manage/Accounts.tsx
  src/pages/admin/home-manage/Links.tsx
  src/pages/admin/home-manage/PromoImage.tsx
  src/pages/admin/home-manage/Reviews.tsx
  src/pages/admin/login/Login.tsx
  src/pages/admin/seminar-live/Attendance.tsx
  src/pages/admin/seminar-manage/Add.tsx
  src/pages/admin/seminar-manage/Applicants.tsx
  src/pages/admin/seminar-manage/Cards.tsx
  src/pages/admin/seminar-manage/Detail.tsx
  src/pages/user/home/Home.tsx
  src/pages/user/notice/Home.tsx
  src/pages/user/notice/Inquiry.tsx
  src/pages/user/notice/Qna.tsx
  src/pages/user/seminar/Apply.tsx
  src/pages/user/seminar/Detail.tsx
  src/pages/user/seminar/Home.tsx
  src/pages/user/seminar/Live.tsx
  src/pages/user/seminar/Review.tsx
  src/pages/user/speakers/Detail.tsx
  src/pages/user/speakers/List.tsx
  tsconfig.json
Labels: ⚙ Setting, 준희

#33 [FIX] ESLint와 Prettier 충돌로 인한 개행 문제 해결
  eslint.config.js
  package-lock.json
  package.json
Labels: 🐞 BugFix, 유민

#46 [FEAT] 어드민 파일(이미지) 추가 컴포넌트 구현
  src/assets/icons/common/delete.svg
  src/components/admin/upload/AdminFileUpload.tsx
  src/components/admin/upload/AdminImageUpload.tsx
  src/components/admin/upload/AdminPresentationUpload.tsx
  src/pages/admin/home-manage/PromoImage.tsx
Labels: 🎨 Html&css, 윤지

#41 [MOD] 어드민 사이드바 수정
  src/layouts/admin/Sidebar.tsx
Labels: 🎨 Html&css, 준희

#53 [UI] 어드민 세미나 신청자 관리 - SEMI_APPL_001 페이지 구현
  src/App.tsx
  src/components/admin/applicants/ApplicantsList.tsx
  src/pages/admin/seminar-manage/Applicants.tsx
  src/pages/admin/seminar-manage/applicants/Detail.tsx
  src/pages/admin/seminar-manage/applicants/List.tsx
  src/pages/admin/seminar-manage/applicants/Questions.tsx
Labels: 🎨 Html&css, 준희

#49 [UI] 어드민 홈 화면 관리 - 홍보 사진 관리 화면 구현
  src/pages/admin/home-manage/PromoImage.tsx
Labels: 🎨 Html&css, 윤지

#58 [UI] 세미나 홈 ui 구현
  src/components/Chip/ChipSeminar.tsx
  src/components/Semina/SeminaListCard.tsx
  src/components/Seminar/SeminarListCard.tsx
  src/pages/user/seminar/Home.tsx
Labels: 🎨 Html&css, 수진

#51 [UI] 어드민 홈 화면 관리 - 링크 관리 화면 구현
  src/pages/admin/home-manage/Links.tsx
Labels: 🎨 Html&css, 윤지

#65 [UI] 강연 카드 캐러셀 구현
  src/components/LectureCard/Carousel.tsx
  src/components/LectureCard/LectureCardMain.tsx
  src/components/LectureCard/LectureCardSession.tsx
  src/components/LectureCard/LectureCardSpeaker.tsx
  src/pages/user/home/Home.tsx
Labels: 🎨 Html&css, 채윤

#64 [UI] 어드민 연사진 정보 입력 컴포넌트 구현
  src/components/admin/SeminarManage/SingleSpeakerForm.tsx
  src/components/admin/SeminarManage/SpeakerForm.tsx
Labels: 🎨 Html&css, 준석

#62 [UI] 어드민 세미나 라이브 링크 컴포넌트 구현
  src/components/admin/SeminarManage/LiveLinkInput.tsx
Labels: 🎨 Html&css, 준석

#71 [UI] 세미나 신청폼 질문하기 페이지 구현
  .gitignore
  .vscode/settings.json
  src/assets/images/sampleSpeaker.svg
  src/components/Button/Button.tsx
  src/components/Chip/Chip.tsx
  src/components/SeminarApply/AutoResizeTextarea.tsx
  src/components/SeminarApply/SpeakerCard.tsx
  src/pages/user/seminar/ApplyInfo.tsx
  src/pages/user/seminar/ApplyQuestion.tsx
Labels: 🎨 Html&css, 유민

#73 [UI] 어드민 후기 목록 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/icons/components/ReviewCard/moremenu.svg
  src/components/admin/SeminarManage/ReivewItem.tsx
  src/components/admin/SeminarManage/ReviewList.tsx
  src/components/admin/SeminarManage/StarRating.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: 🎨 Html&css, 준석
